# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
        exclude: VERSION
      - id: check-yaml
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        language: golang
        entry: golangci-lint run ./...
        pass_filenames: false
        types: [go]
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: go-unit-tests
        name: run go test s(go test)
        language: system
        entry: make test
        pass_filenames: false
        types: [go]
        files: ^subdir/
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: commit-msg
        name: commit message checking
        language: system
        entry: make commit-msg
        pass_filenames: true
        stages: [commit-msg]
